{{- range tuple "A" "B" -}}
{{- if or (eq $.Values.mainTrack .) $.Values.canaryEnabled -}}
{{- $track := (pick $.Values (printf "track%s" .)) | values | first }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "canary-chart.fullname" $ }}-a
  labels:
    app.kubernetes.io/name: {{ include "canary-chart.name" $ }}
    helm.sh/chart: {{ include "canary-chart.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    track: {{ . }}
spec:
  replicas: {{ div (mul (include "canary-chart.weight" (tuple $ .)) $.Values.replicaCount) 100 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "canary-chart.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      track: {{ . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "canary-chart.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        track: {{ . }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $track.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
---
{{- end }}
{{- end }}
