apiVersion: v1
kind: Service
metadata:
  name: {{ include "canary-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "canary-chart.name" . }}
    helm.sh/chart: {{ include "canary-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    getambassador.io/config: |
      {{- range tuple "A" "B" -}}
      {{- if or (eq $.Values.mainTrack .) $.Values.offTrackEnabled }}
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: {{ include "canary-chart.fullname" $ }}_mapping-A
      prefix: {{ $.Values.ambassador.path  }}
      service: {{ $.Release.Name }}-{{ . }}
      weight: {{ include "canary-chart.weight" (tuple $ .) }}
      {{- end }}
      {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "canary-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
