{{- $fullName := include "canary-chart.fullname" . -}}
{{- $name := include "canary-chart.name" . -}}
{{- range tuple "A" "B" -}}
{{- $service := printf "%s-%s.%s.svc" $.Release.Name . $.Release.Namespace -}}
{{- if or (eq $.Values.mainTrack .) $.Values.canaryEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ . }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ include "canary-chart.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: {{ $fullName }}_mapping-{{ . }}
      prefix: /my-service/
      service: {{ $service }}
      weight: {{ include "canary-chart.weight" (tuple $ .) }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    track: {{ . }}
---
{{- end }}
{{- end }}
